### ISSUE TITLE
If my inputs are correct, I login successfully and see my dashboard

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#145] opened 2020-03-27 10:14 UTC
__Is there an associated User Story?__

#143 #144 

__Is this part of a User Journey?__

#142 
---

### Acceptance Criteria:
- [ ] Error message if password / email don't match

**Comment by thejoefriel** [comment] 2020-03-29 17:33
this is a duplicate of #25

**Closed by thejoefriel** 2020-03-29 17:33 UTC
Labels: backlog, spend-partner
