### ISSUE TITLE
I go to the url I have been given and see a log in page with email, password fields 

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#143] opened 2020-03-27 10:11 UTC
__Is this part of a User Journey?__
#142 

### Acceptance Criteria:
- [ ] Tempo logo / banner (make sure this is evident throughout the entire journey)
- [ ] Email field (basic on blur validation to test it is a standard email)
- [ ] Password field
- [ ] Log In Button
- [ ] Accept Time Credits without logging in link

**Comment by thejoefriel** [comment] 2020-03-29 17:34
This is a duplicate of #25

**Closed by thejoefriel** 2020-03-29 17:34 UTC
Labels: backlog, spend-partner
