### ISSUE TITLE
For each volunteer I can see their name, the total number of Time Credits I have given them, the % they have spent, a checkbox to say they no longer volunteer here

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#119] opened 2020-03-10 18:03 UTC
__Is there an associated User Story?__

#118 

__Is this part of a User Journey?__

#117

**Comment by thejoefriel** [comment] 2020-03-29 17:21
duplicate of #87

**Closed by thejoefriel** 2020-03-29 17:21 UTC
Labels: backlog, customer
